### ISSUE TITLE
No API token found for service account sonobuoy-serviceaccount on Azure

### ISSUE THREAD

**Issue by ydp** [vmware-tanzu/sonobuoy#1203] opened 2021-01-04 08:06 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

1.  Deploy TKGi on Azure
2.  run sonobuoy (0.19.0)
```
root@90d96b0a-f515-461f-4ab2-37165be66356:/tmp/build/483c3cf5# sonobuoy delete --wait
INFO[0000] deleted                                       kind=namespace namespace=sonobuoy
INFO[0000] deleted                                       kind=clusterrolebindings
INFO[0000] deleted                                       kind=clusterroles
root@90d96b0a-f515-461f-4ab2-37165be66356:/tmp/build/483c3cf5# sonobuoy run --plugin e2e --wait --e2e-focus '\[sig-network\].*Conformance' --e2e-skip '\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[sig-cli\]|\[sig-storage\]|\[sig-auth\]|\[sig-api-machinery\]|\[sig-apps\]|\[sig-node\]' --sonobuoy-image projects.registry.vmware.com/sonobuoy/sonobuoy:v0.19.0 --e2e-repo-config /tmp/build/483c3cf5/kubo-odb-ci/antrea/scripts/conformance-image-config.yaml
INFO[0000] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0001] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0001] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0001] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterroles
INFO[0001] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0001] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
ERRO[0011] error attempting to run sonobuoy: failed to create object: failed to create API resource sonobuoy: No API token found for service account "sonobuoy-serviceaccount", retry after the token is automatically created and added to the service account
root@90d96b0a-f515-461f-4ab2-37165be66356:/tmp/build/483c3cf5# sonobuoy run --plugin e2e --wait --e2e-focus '\[sig-network\].*Conformance' --e2e-skip '\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[sig-cli\]|\[sig-storage\]|\[sig-auth\]|\[sig-api-machinery\]|\[sig-apps\]|\[sig-node\]' --sonobuoy-image projects.registry.vmware.com/sonobuoy/sonobuoy:v0.19.0 --e2e-repo-config /tmp/build/483c3cf5/kubo-odb-ci/antrea/scripts/conformance-image-config.yaml
ERRO[0000] Preflight checks failed
ERRO[0000] namespace already exists
```

**What did you expect to happen:**

run successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version:  0.19.0
- Kubernetes version: (use `kubectl version`):  v1.19.4+vmware.2
- Kubernetes installer & version: 
- Cloud provider or hardware configuration:   Azure
- OS (e.g. from `/etc/os-release`):  Ubuntu 16.04.7 LTS
- Sonobuoy tarball (which contains * below): sonobuoy_0.19.0_linux_amd64.tar.gz

**Comment by ydp** [comment] 2021-01-04 08:12
Looks like retry several times, it can run successfully.

**Comment by wilsonehusin** [comment] 2021-01-04 20:49
and this is only happening on Azure but not other cloud providers?

**Comment by ydp** [comment] 2021-01-05 00:13
Yes, it only happens on Azure. After I upgrade to sonobuoy 0.20.0, it still reveals.

**Comment by ydp** [comment] 2021-01-07 00:49
After I tried the method suggested by @wilsonehusin : 
```
+ sonobuoy gen --plugin e2e --e2e-focus '\[sig-network\].*Conformance' --e2e-skip '\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[sig-cli\]|\[sig-storage\]|\[sig-auth\]|\[sig-api-machinery\]|\[sig-apps\]|\[sig-node\]' --sonobuoy-image projects.registry.vmware.com/sonobuoy/sonobuoy:v0.20.0 --e2e-repo-config /tmp/build/483c3cf5/kubo-odb-ci/antrea/scripts/conformance-image-config.yaml
+ kubectl apply -f -
namespace/sonobuoy created
serviceaccount/sonobuoy-serviceaccount created
clusterrolebinding.rbac.authorization.k8s.io/sonobuoy-serviceaccount-sonobuoy created
clusterrole.rbac.authorization.k8s.io/sonobuoy-serviceaccount-sonobuoy created
configmap/sonobuoy-config-cm created
configmap/sonobuoy-plugins-cm created
pod/sonobuoy created
configmap/repolist-cm created
service/sonobuoy-aggregator created
+ kubectl get pods -n sonobuoy
NAME       READY   STATUS              RESTARTS   AGE
sonobuoy   0/1     ContainerCreating   0          1s
+ kubectl describe po sonobuoy -n sonobuoy
Name:         sonobuoy
Namespace:    sonobuoy
Priority:     0
Node:         5177ba10-f3a6-45db-97c1-488aba1ab7e1/10.0.16.15
Start Time:   Wed, 06 Jan 2021 09:57:04 +0000
Labels:       component=sonobuoy
              run=sonobuoy-master
              sonobuoy-component=aggregator
              tier=analysis
Annotations:  kubernetes.io/psp: e2e-test-privileged-psp
Status:       Pending
IP:
IPs:          <none>
Containers:
  kube-sonobuoy:
    Container ID:
    Image:          projects.registry.vmware.com/sonobuoy/sonobuoy:v0.20.0
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      SONOBUOY_ADVERTISE_IP:   (v1:status.podIP)
    Mounts:
      /etc/sonobuoy from sonobuoy-config-volume (rw)
      /plugins.d from sonobuoy-plugins-volume (rw)
      /tmp/sonobuoy from output-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from sonobuoy-serviceaccount-token-544rn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  sonobuoy-config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sonobuoy-config-cm
    Optional:  false
  sonobuoy-plugins-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sonobuoy-plugins-cm
    Optional:  false
  output-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  sonobuoy-serviceaccount-token-544rn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  sonobuoy-serviceaccount-token-544rn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     kubernetes.io/e2e-evict-taint-key op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  1s    default-scheduler  Successfully assigned sonobuoy/sonobuoy to 5177ba10-f3a6-45db-97c1-488aba1ab7e1
  Normal  Pulled     0s    kubelet            Container image "projects.registry.vmware.com/sonobuoy/sonobuoy:v0.20.0" already present on machine
  Normal  Created    0s    kubelet            Created container kube-sonobuoy
+ sonobuoy status
ERRO[0000] error attempting to run sonobuoy: pod has status "Pending"
```
then, I go back check sonobuoy results, found that there are logs presented, show former run success. so after some search, found this:
https://github.com/kubernetes/kubernetes/issues/67882
As the guy liggitt suggested:
```
 Launching a pod directly in a manifest (as opposed to a workload object like a daemonset, replicaset, or job) isn't usually recommended, since it's not robust in the face of failures or errors.
```
and 
```
Running in an underpowered environment can increase the lag if the controller manager takes longer to provision the dependent objects
```
maybe this is the cause of my failure, could anyone look into this? and is there any workaround here regarding 0.20.0?

**Comment by wilsonehusin** [comment] 2021-01-07 01:16
a couple of things:
1. `sonobuoy run $FLAGS` is practically `sonobuoy gen $FLAGS | kubectl apply -f -`, except the `--wait` flag on `sonobuoy run` will wait for the operations to finish. the fact that using `gen` completes the tests, it means that CLI timed out, but the cluster still put in efforts to run the tasks.
2. Launching a pod directly in this case isn't quite relevant to the whole problem, service account creation happened from CLI, not from in-cluster container.
3. Underpowered environment sounds possible, I'd suggest looking into your tile configurations in OpsMan to see how your cluster size is configured.
4. I believe this problem is out of scope for Sonobuoy project -- Sonobuoy is working as intended to surface the problem (service account creation takes too long to finish)

**Closed by wilsonehusin** 2021-01-07 01:16 UTC
