### ISSUE TITLE
Missing Conformance tests skipped by disruptive with _certified-conformance_ mode

### ISSUE THREAD

**Issue by BobyMCbobs** [vmware-tanzu/sonobuoy#1388] opened 2021-08-16 03:31 UTC
**What steps did you take and what happened:**
When I ran
```shell
sonobuoy run --mode=certified-conformance
```
Conformance tests that have the disruptive label were ignored with the _certified-conformance_ mode.

**What did you expect to happen:**
Disruptive tests should be run with the _certified-conformance_ mode as they are required by Conformance.

**Anything else you would like to add:**
In the sonobuoy-plugins-0 ConfigMap, there
```
$ kubectl -n sonobuoy get cm sonobuoy-plugins-cm -o=jsonpath='{.data.plugin-0\.yaml}' | yq e .spec.env[3] -P -
name: E2E_SKIP
value: \[Disruptive\]|NoExecuteTaintManager
```

I also noticed the logic
https://github.com/vmware-tanzu/sonobuoy/blob/master/cmd/sonobuoy/app/args.go#L457
for choosing the args

A workaround that I had was to run
```
sonobuoy run --mode=certified-conformance --plugin-env e2e.E2E_SKIP=''
```

**Environment:**

- Sonobuoy version: v0.53.1
- Kubernetes version: (use `kubectl version`): v1.21.2
- Kubernetes installer & version: `kind` v0.11.1
- Cloud provider or hardware configuration: nil
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04
- Sonobuoy tarball (which contains * below)

**Comment by tedli** [comment] 2021-08-16 07:16
I think it's because of this line,
https://github.com/vmware-tanzu/sonobuoy/blob/0f7c4a222f334c9b957843f36410713fa14f1946/cmd/sonobuoy/app/args.go#L203
`mode` is hardcoded set to `NonDisruptiveConformance` to act as a default behavior, however, this caused the `E2E_SKIP` env set.
Then by specifying `--mode` to `certified-conformance` could trigger mode set again, but without clearing the already set `E2E_SKIP`.

There goes this problem.

**Comment by johnSchnake** [comment] 2021-08-16 14:19
confirmed the issue; will patch asap and push a new release. Will check various versions to find when the regression landed (though I have a guess) and push a new version.

**Closed** 2021-08-16 15:51 UTC
Labels: bug, p0 - Higher Priority
