### ISSUE TITLE
sonobuoy status not reporting correctly while e2e tests are running 

### ISSUE THREAD

**Issue by matthias50** [vmware-tanzu/sonobuoy#1507] opened 2021-11-04 13:46 UTC
**What steps did you take and what happened:**
`sonobuoy status` is intermittently not reporting on the status of the tests while they are running despite the logs confirming that tests are indeed running and passing.
```
$ sonobuoy status
         PLUGIN     STATUS   RESULT   COUNT   PROGRESS
            e2e    running                1
   systemd-logs   complete               13
$ sonobuoy logs | grep Conformance
Args (comma-delimited): /usr/local/bin/ginkgo,--focus=\[Conformance\],--skip=\[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|(should\sprovide\sDNS\sfor\sservices)|(should\sbe\sable\sto\schange\sthe\stype\sfrom\sExternalName\sto\sNodePort)|(should\sbe\sable\sto\screate\sa\sfunctioning\sNodePort\sservice)|(should\shave\ssession\saffinity\swork\sfor\sNodePort\sservice)|(should\shave\ssession\saffinity\stimeout\swork\sfor\sNodePort\sservice)|(should\sbe\sable\sto\sswitch\ssession\saffinity\sfor\sNodePort\sservice),--noColor=true,/usr/local/bin/e2e.test,--,--disable-log-dump,--repo-root=/kubernetes,--provider=local,--report-dir=/tmp/results,--kubeconfig=,--non-blocking-taints=workload,node-role.kubernetes.io/master
  should create a ResourceQuota and capture the life of a replica set. [Conformance]
[It] should create a ResourceQuota and capture the life of a replica set. [Conformance]
  should create a ResourceQuota and capture the life of a replica set. [Conformance]
{"msg":"PASSED [sig-api-machinery] ResourceQuota should create a ResourceQuota and capture the life of a replica set. [Conformance]","total":297,"completed":1,"skipped":0,"failed":0}
  should be able to convert a non homogeneous list of CRs [Conformance]
[It] should be able to convert a non homogeneous list of CRs [Conformance]
  should be able to convert a non homogeneous list of CRs [Conformance]
{"msg":"PASSED [sig-api-machinery] CustomResourceConversionWebhook [Privileged:ClusterAdmin] should be able to convert a non homogeneous list of CRs [Conformance]","total":297,"completed":2,"skipped":15,"failed":0}

(partial logs only. there are many more entries just like this)
```

**What did you expect to happen:**
`sonobuoy status` reports on the running tests

**Anything else you would like to add:**
This sometimes works and sometimes doesn't

**Environment:**

- Sonobuoy version: v0.53.2
- Kubernetes version: (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: Custom in house deployment 
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment] 2021-11-04 13:50
> intermittently not reporting on the status of the tests while they are running

Making sure I understand the report; are you pointing out how the `PROGRESS` column is not being filled in despite the logs showing the progress? That does seem odd based on the output you showed me.

If you could upload/send me a full results tarball so I can dig into the logs it would help.

**Comment by matthias50** [comment] 2021-11-04 14:38
> Making sure I understand the report; are you pointing out how the PROGRESS column is not being filled in despite the logs showing the progress?

Yes. That's what we are seeing. Here is the json version in case that is helpful. I'll have to check if I can upload the full tarball or not. Lots of stuff in there.

In the interim, here is what `sonobuoy status --json` reports (node names redacted) if this helps.

```
$ sonobuoy status --json | jq '.'

{
    "plugins": [
      {
        "plugin": "e2e",
        "node": "global",
        "status": "running",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      },
      {
        "plugin": "systemd-logs",
        "node": "redacted",
        "status": "complete",
        "result-status": "",
        "result-counts": null
      }
    ],
    "status": "running",
    "tar-info": {
      "name": "",
      "created": "0001-01-01T00:00:00Z",
      "sha256": "",
      "size": 0
    }
  }

```

**Comment by johnSchnake** [comment] 2021-11-04 15:24
OK thanks for the clarification; from that `--json` output I can see that the e2e status shows as empty ```{
        "plugin": "e2e",
        "node": "global",
        "status": "running",
        "result-status": "",
        "result-counts": null
      },``` which isn't right if it came from a run that had been going for a while.

That does sound like a bug that could have crept in: the progress can periodically get removed from the status. I'm not certain why that would have happened but I know where to look and try and reproduce the issue.

**Comment by johnSchnake** [comment] 2021-11-10 19:21
The main thing I would want from the tarball (in case it is easier to provide):
 - the aggregator logs (it should be logging when it gets progress updates)
 - the sonobuoy-worker logs for the container in the e2e pod
 - the e2e logs
 - the resources/ns/sonobuoy/<pods or v1_pods or whatever its called>

The e2e logs you gave me tidbits of, so I know those events are occurring but I'd need to see the logs in their entirety in order to check how the tests were invoked.

The e2e container should be sending them to the worker
The worker should be getting them and transmitting them to the aggregator
The aggregator should be getting them and updating its status

Going to peek around in code but it would really help to narrow it down if you could provide the above files.

**Comment by matthias50** [comment] 2021-11-15 20:11
I have a tarball from a run where this occurred. Can you point me to the specific files you would need for these points:

> the aggregator logs (it should be logging when it gets progress updates)
> the sonobuoy-worker logs for the container in the e2e pod
> the e2e logs

Its hard for me to get logs from when this is happening live because the testing happens while I sleep and then everything is torn down by the morning.

**Comment by johnSchnake** [comment] 2021-11-17 20:00
the aggregator logs (it should be logging when it gets progress updates)
 - `meta/run.log`
the sonobuoy-worker logs for the container in the e2e pod
 - `podlogs/sonobuoy/sonobuoy-e2e-job-<....>/logs/sonobuoy-worker.txt`
the e2e logs
 - `podlogs/sonobuoy/sonobuoy-e2e-job-<....>/logs/e2e.txt`

And any files under `resources/ns/sonobuoy/`

**Comment by matthias50** [comment] 2021-11-18 17:48
Ok. I'll work on sanitizing these logs. Unfortunately, I need to redact all the hostnames and IP addresses and there are a lot of them.

In the interim, I noticed that the worker logs aren't in the podlogs dir.

```
$ find podlogs
podlogs
podlogs/sonobuoy
podlogs/sonobuoy/sonobuoy
podlogs/sonobuoy/sonobuoy/logs
podlogs/sonobuoy/sonobuoy/logs/kube-sonobuoy.txt
```

**Comment by johnSchnake** [comment] 2021-11-18 19:51
So you don't have the worker logs or the e2e logs themselves?

The meta/run.log is about the same as the logs/kube-sonobuoy.txt; it would be useful but not as much as if we had those along with the e2e worker & plugin logs.

I'd be happy to try and debug this with you 'live' over zoom or something, we wouldn't record it so the sensitive information wouldn't be persisted if that is OK with your organization.

**Comment by matthias50** [comment] 2021-11-24 17:20
Sorry for the delay. I got approval for this approach. Should I email you to try to set up a time?

**Comment by matthias50** [comment] 2022-01-18 20:07
@johnSchnake, this is still happening on our side. I'm still open to the live debugging option if that works for you.

**Comment by johnSchnake** [comment] 2022-04-05 20:24
For others who find this issue; we were able to debug the issue in person and the issue was that the `--E2E-EXTRA-ARGS` environment variable for the e2e plugin was being overwritten. For progress updates to work, you have to provide the value `--progress-report-url=http://localhost:8099/progress` in that env var. You can add other things to it as well, but without that progress report URL the e2e plugin wont know what to do at to send progress updates.

The reason for this is that the upstream e2e tests don't have Sonobuoy specific stuff hardcoded for the most part; we implemented these progress updates as a generic webhook and we just plug into it.

Thanks for finding the time to go over it with me @matthias50 ; going to close this issue. Feel free to reopen it if it doesn't resolve your issue.

**Closed by johnSchnake** 2022-04-05 20:24 UTC
Labels: bug, UX
